name: Deploy AWS Lambda with Terraform

on:
  push:
    branches:
      - master 

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0 

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
        
      - name: Prepare Lambda package
        run: |
          cd app && pip3 install -r requirements.txt --target ./package && cd package && zip -r ../../deployment-package.zip . && cd .. && zip -ur ../deployment-package.zip . && cd ..
          now=$(date +'%d-%m-%Y-%H-%M')
          mv deployment-package.zip deployment-package_${now}.zip && pkg=deployment-package_${now}.zip
          aws lambda update-function-code --function-name ${{ vars.FUNCTION }} --zip-file fileb://deployment-package_${now}.zip
      

